# get_social_inputs_numpy

In [4]:
import numpy as np

class Object(object):
    pass

args = Object()
args.neighbor_thred = 10

self = Object()
self.args = args

In [161]:
inputnodes = np.array([[[ 5.7826  , 13.018   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 5.7519  , 12.088   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 5.7298  , 11.746   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 5.8362  , 11.175   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 5.8732  , 10.434   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 6.1715  , 10.05    ],
        [ 6.6684  , 12.271   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 6.2374  ,  9.5713  ],
        [ 6.7666  , 11.936   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 6.2638  ,  9.0841  ],
        [ 6.9144  , 11.448   ],
        [ 5.126   , -1.7114  ],
        [ 4.3795  , -1.8861  ],
        [ 5.7482  , 12.163   ]],

       [[ 6.374   ,  8.5528  ],
        [ 6.7983  , 10.826   ],
        [ 5.1061  , -1.119   ],
        [ 4.4582  , -1.282   ],
        [ 5.8503  , 11.675   ]],

       [[ 6.481   ,  8.0979  ],
        [ 6.7861  , 10.394   ],
        [ 5.0864  , -0.53496 ],
        [ 4.4431  , -0.69465 ],
        [ 5.9186  , 11.101   ]],

       [[ 6.5483  ,  7.6354  ],
        [ 6.8606  ,  9.8409  ],
        [ 5.0196  ,  0.089118],
        [ 4.2429  , -0.078294],
        [ 5.9088  , 10.515   ]],

       [[ 6.6165  ,  7.1671  ],
        [ 6.8512  ,  9.3565  ],
        [ 4.9975  ,  0.75858 ],
        [ 4.2271  ,  0.59534 ],
        [ 5.895   ,  9.9982  ]],

       [[ 6.6415  ,  6.7342  ],
        [ 6.7963  ,  8.9454  ],
        [ 4.9324  ,  1.3634  ],
        [ 4.1674  ,  1.2039  ],
        [ 6.0033  ,  9.439   ]],

       [[ 6.7059  ,  6.3426  ],
        [ 6.8699  ,  8.4109  ],
        [ 4.8683  ,  1.9594  ],
        [ 4.1086  ,  1.8035  ],
        [ 6.0304  ,  8.9085  ]],

       [[ 6.7684  ,  5.9915  ],
        [ 6.8577  ,  7.9486  ],
        [ 4.8479  ,  2.5987  ],
        [ 4.0943  ,  2.4466  ],
        [ 6.015   ,  8.4098  ]],

       [[ 6.9182  ,  5.5974  ],
        [ 6.807   ,  7.4355  ],
        [ 4.7838  ,  3.2247  ],
        [ 4.0348  ,  3.1247  ],
        [ 6.0836  ,  7.8661  ]],

       [[ 6.9822  ,  5.2395  ],
        [ 6.8356  ,  6.9627  ],
        [ 4.7659  ,  3.7967  ],
        [ 4.0224  ,  3.6993  ],
        [ 6.1487  ,  7.4001  ]],

       [[ 7.0384  ,  5.0151  ],
        [ 6.9838  ,  6.5785  ],
        [ 4.6991  ,  4.5437  ],
        [ 4.0526  ,  4.3153  ],
        [ 6.136   ,  6.8367  ]],

       [[ 7.2222  ,  4.7976  ],
        [ 7.0111  ,  6.1392  ],
        [ 4.6793  ,  5.188   ],
        [ 4.0381  ,  4.9646  ],
        [ 6.1606  ,  6.3553  ]],

       [[ 7.5799  ,  4.544   ],
        [ 7.0778  ,  5.7418  ],
        [ 4.7037  ,  5.7793  ],
        [ 4.0678  ,  5.5605  ],
        [ 6.2276  ,  5.87    ]]])

In [162]:
inputnodes = np.array([[
    [1, 1],
    [0, 0]],

    [[1, 1],
    [0,  0]]])

In [163]:
def get_social_inputs_numpy(self, inputnodes):
    '''
    Get the sequence list (denoting where data exists) and neighboring
    list (denoting where neighbors exists).
    '''
    num_Peds = inputnodes.shape[1]

    seq_list = np.zeros((inputnodes.shape[0], num_Peds))
    # denote where data not missing

    for pedi in range(num_Peds):
        seq = inputnodes[:, pedi]
        seq_list[seq[:, 0] != 0, pedi] = 1

    # get relative cords, neighbor id list
    nei_list = np.zeros((inputnodes.shape[0], num_Peds, num_Peds))
    nei_num = np.zeros((inputnodes.shape[0], num_Peds))

    # nei_list[f,i,j] denote if j is i's neighbors in frame f
    for pedi in range(num_Peds):
        # the default is that everyone is neighbor (where data exists)
        nei_list[:, pedi, :] = seq_list
        nei_list[:, pedi, pedi] = 0  # person i is not neighbor of itself
        nei_num[:, pedi] = np.sum(nei_list[:, pedi, :], axis=1)  # count
        seqi = inputnodes[:, pedi]
        for pedj in range(num_Peds):
            seqj = inputnodes[:, pedj]
            # where both sequences have data
            select = (seq_list[:, pedi] > 0) & (seq_list[:, pedj] > 0)

            relative_cord = seqi[select, :2] - seqj[select, :2]

            # indices where pedi and pedj are not neighors
            select_dist = (abs(relative_cord[:, 0]) > self.args.neighbor_thred) | (
                    abs(relative_cord[:, 1]) > self.args.neighbor_thred)

            # TODO: use l2_norm > L for distance instead of x>L or y>L
#             select_dist_2 = np.linalg.norm(relative_cord,
#                                            axis=1) > self.args.neighbor_thred

            nei_num[select, pedi] -= select_dist

            select[select == True] = select_dist
            nei_list[select, pedi, pedj] = 0
    return seq_list, nei_list, nei_num

In [164]:
seq_list, nei_list, nei_num = get_social_inputs_numpy(self, inputnodes)

In [165]:
seq_list

array([[1., 0.],
       [1., 0.]])

In [166]:
nei_list

array([[[0., 0.],
        [1., 0.]],

       [[0., 0.],
        [1., 0.]]])

In [167]:
nei_num

array([[0., 1.],
       [0., 1.]])

In [181]:
neighbor_thred = 10

In [182]:
array1 = np.array([[
    [1, 1],
    [2, 2]],

    [[1, 1],
    [12,  12]]])

In [183]:
array2 = np.array([[
    [1, 1],
    [2, 2],
    [3, 3],],

    [[1, 1],
    [12,  12],
    [10, 10]]])

In [221]:
array3 = np.array([[[ 5.7826  , 13.018   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 5.7519  , 12.088   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 5.7298  , 11.746   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 5.8362  , 11.175   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 5.8732  , 10.434   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 6.1715  , 10.05    ],
        [ 6.6684  , 12.271   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 6.2374  ,  9.5713  ],
        [ 6.7666  , 11.936   ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ],
        [ 0.      ,  0.      ]],

       [[ 6.2638  ,  9.0841  ],
        [ 6.9144  , 11.448   ],
        [ 5.126   , -1.7114  ],
        [ 4.3795  , -1.8861  ],
        [ 5.7482  , 12.163   ]],

       [[ 6.374   ,  8.5528  ],
        [ 6.7983  , 10.826   ],
        [ 5.1061  , -1.119   ],
        [ 4.4582  , -1.282   ],
        [ 5.8503  , 11.675   ]],

       [[ 6.481   ,  8.0979  ],
        [ 6.7861  , 10.394   ],
        [ 5.0864  , -0.53496 ],
        [ 4.4431  , -0.69465 ],
        [ 5.9186  , 11.101   ]],

       [[ 6.5483  ,  7.6354  ],
        [ 6.8606  ,  9.8409  ],
        [ 5.0196  ,  0.089118],
        [ 4.2429  , -0.078294],
        [ 5.9088  , 10.515   ]],

       [[ 6.6165  ,  7.1671  ],
        [ 6.8512  ,  9.3565  ],
        [ 4.9975  ,  0.75858 ],
        [ 4.2271  ,  0.59534 ],
        [ 5.895   ,  9.9982  ]],

       [[ 6.6415  ,  6.7342  ],
        [ 6.7963  ,  8.9454  ],
        [ 4.9324  ,  1.3634  ],
        [ 4.1674  ,  1.2039  ],
        [ 6.0033  ,  9.439   ]],

       [[ 6.7059  ,  6.3426  ],
        [ 6.8699  ,  8.4109  ],
        [ 4.8683  ,  1.9594  ],
        [ 4.1086  ,  1.8035  ],
        [ 6.0304  ,  8.9085  ]],

       [[ 6.7684  ,  5.9915  ],
        [ 6.8577  ,  7.9486  ],
        [ 4.8479  ,  2.5987  ],
        [ 4.0943  ,  2.4466  ],
        [ 6.015   ,  8.4098  ]],

       [[ 6.9182  ,  5.5974  ],
        [ 6.807   ,  7.4355  ],
        [ 4.7838  ,  3.2247  ],
        [ 4.0348  ,  3.1247  ],
        [ 6.0836  ,  7.8661  ]],

       [[ 6.9822  ,  5.2395  ],
        [ 6.8356  ,  6.9627  ],
        [ 4.7659  ,  3.7967  ],
        [ 4.0224  ,  3.6993  ],
        [ 6.1487  ,  7.4001  ]],

       [[ 7.0384  ,  5.0151  ],
        [ 6.9838  ,  6.5785  ],
        [ 4.6991  ,  4.5437  ],
        [ 4.0526  ,  4.3153  ],
        [ 6.136   ,  6.8367  ]],

       [[ 7.2222  ,  4.7976  ],
        [ 7.0111  ,  6.1392  ],
        [ 4.6793  ,  5.188   ],
        [ 4.0381  ,  4.9646  ],
        [ 6.1606  ,  6.3553  ]],

       [[ 7.5799  ,  4.544   ],
        [ 7.0778  ,  5.7418  ],
        [ 4.7037  ,  5.7793  ],
        [ 4.0678  ,  5.5605  ],
        [ 6.2276  ,  5.87    ]]])

In [222]:
def get_social_inputs_numpy_Filippo(self, inputnodes):
    '''
    Get the sequence list (denoting where data exists) and neighboring
    list (denoting where neighbors exists) and number.
    '''

    num_Peds = inputnodes.shape[1]

    seq_list = np.zeros((inputnodes.shape[0], num_Peds))
    # denote where data not missing

    for pedi in range(num_Peds):
        seq = inputnodes[:, pedi]
        seq_list[seq[:, 0] != 0, pedi] = 1

    # get relative cords, neighbor id list
    nei_list = np.zeros((inputnodes.shape[0], num_Peds, num_Peds))

    # nei_list[f,i,j] denote if j is i's neighbor in frame f
    for pedi in range(num_Peds):
        seqi = inputnodes[:, pedi]
        for pedj in range(num_Peds):
            # person i is not neighbor of itself
            if pedi == pedj:
                continue
            both_present = seq_list[:, [pedi, pedj]].all(axis=1)
            seqj = inputnodes[:, pedj]
            relative_cord = seqi[:, :2] - seqj[:, :2]
            # indices where pedi and pedj are neighbors
            select_dist = np.linalg.norm(relative_cord, axis=1) < neighbor_thred
            neighbors_bool = np.logical_and(both_present, select_dist)
            nei_list[:, pedi, pedj] = neighbors_bool
    
    # number of neighbors
    nei_num = nei_list.sum(axis=1)
    
    # TESTS
    def check_symmetric(a, rtol=1e-05, atol=1e-08):
        return np.allclose(a, a.T, rtol=rtol, atol=atol)
    def check_all_symmetric(arr):
        return all(check_symmetric(a) for a in arr)
    assert nei_num.shape == (inputnodes.shape[0], num_Peds)
    assert check_all_symmetric(nei_list)
    
    return seq_list, nei_list, nei_num

In [216]:
array1 = np.array([[
    [1, 1],
    [10, 10]],

    [[1, 1],
    [0,  0]]])

In [223]:
seq_list, nei_list, nei_num = get_social_inputs_numpy_Filippo(self, array3)

In [224]:
seq_list

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [225]:
nei_list

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]

In [226]:
nei_num

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [2., 2., 1., 1., 2.],
       [3., 2., 2., 1., 2.],
       [4., 2., 2., 2., 2.],
       [4., 3., 3., 2., 2.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])